/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ShareRouteImport } from './routes/share'
import { Route as TeamsNewRouteImport } from './routes/teams.new'
import { Route as GamesGameIdIndexRouteImport } from './routes/games.$gameId.index'
import { Route as GamesGameIdFairnessRouteImport } from './routes/games.$gameId.fairness'
import { Route as GamesGameIdSummaryRouteImport } from './routes/games.$gameId.summary'
import { Route as TeamsTeamIdNewGameRouteImport } from './routes/teams.$teamId.new-game'
import { Route as TeamsTeamIdRosterRouteImport } from './routes/teams.$teamId.roster'
import { Route as TeamsTeamIdSeasonRouteImport } from './routes/teams.$teamId.season'
import { Route as TeamsTeamIdSettingsRouteImport } from './routes/teams.$teamId.settings'
import { Route as TeamsTeamIdPlayersPlayerIdRouteImport } from './routes/teams.$teamId.players.$playerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdIndexRoute = GamesGameIdIndexRouteImport.update({
  id: '/games/$gameId/',
  path: '/games/$gameId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdFairnessRoute = GamesGameIdFairnessRouteImport.update({
  id: '/games/$gameId/fairness',
  path: '/games/$gameId/fairness',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdSummaryRoute = GamesGameIdSummaryRouteImport.update({
  id: '/games/$gameId/summary',
  path: '/games/$gameId/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdNewGameRoute = TeamsTeamIdNewGameRouteImport.update({
  id: '/teams/$teamId/new-game',
  path: '/teams/$teamId/new-game',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRosterRoute = TeamsTeamIdRosterRouteImport.update({
  id: '/teams/$teamId/roster',
  path: '/teams/$teamId/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdSeasonRoute = TeamsTeamIdSeasonRouteImport.update({
  id: '/teams/$teamId/season',
  path: '/teams/$teamId/season',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdSettingsRoute = TeamsTeamIdSettingsRouteImport.update({
  id: '/teams/$teamId/settings',
  path: '/teams/$teamId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdPlayersPlayerIdRoute =
  TeamsTeamIdPlayersPlayerIdRouteImport.update({
    id: '/teams/$teamId/players/$playerId',
    path: '/teams/$teamId/players/$playerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/share': typeof ShareRoute
  '/teams/new': typeof TeamsNewRoute
  '/games/$gameId/fairness': typeof GamesGameIdFairnessRoute
  '/games/$gameId/summary': typeof GamesGameIdSummaryRoute
  '/teams/$teamId/new-game': typeof TeamsTeamIdNewGameRoute
  '/teams/$teamId/roster': typeof TeamsTeamIdRosterRoute
  '/teams/$teamId/season': typeof TeamsTeamIdSeasonRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
  '/games/$gameId/': typeof GamesGameIdIndexRoute
  '/teams/$teamId/players/$playerId': typeof TeamsTeamIdPlayersPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/share': typeof ShareRoute
  '/teams/new': typeof TeamsNewRoute
  '/games/$gameId/fairness': typeof GamesGameIdFairnessRoute
  '/games/$gameId/summary': typeof GamesGameIdSummaryRoute
  '/teams/$teamId/new-game': typeof TeamsTeamIdNewGameRoute
  '/teams/$teamId/roster': typeof TeamsTeamIdRosterRoute
  '/teams/$teamId/season': typeof TeamsTeamIdSeasonRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
  '/games/$gameId': typeof GamesGameIdIndexRoute
  '/teams/$teamId/players/$playerId': typeof TeamsTeamIdPlayersPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/share': typeof ShareRoute
  '/teams/new': typeof TeamsNewRoute
  '/games/$gameId/fairness': typeof GamesGameIdFairnessRoute
  '/games/$gameId/summary': typeof GamesGameIdSummaryRoute
  '/teams/$teamId/new-game': typeof TeamsTeamIdNewGameRoute
  '/teams/$teamId/roster': typeof TeamsTeamIdRosterRoute
  '/teams/$teamId/season': typeof TeamsTeamIdSeasonRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
  '/games/$gameId/': typeof GamesGameIdIndexRoute
  '/teams/$teamId/players/$playerId': typeof TeamsTeamIdPlayersPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/share'
    | '/teams/new'
    | '/games/$gameId/fairness'
    | '/games/$gameId/summary'
    | '/teams/$teamId/new-game'
    | '/teams/$teamId/roster'
    | '/teams/$teamId/season'
    | '/teams/$teamId/settings'
    | '/games/$gameId/'
    | '/teams/$teamId/players/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/share'
    | '/teams/new'
    | '/games/$gameId/fairness'
    | '/games/$gameId/summary'
    | '/teams/$teamId/new-game'
    | '/teams/$teamId/roster'
    | '/teams/$teamId/season'
    | '/teams/$teamId/settings'
    | '/games/$gameId'
    | '/teams/$teamId/players/$playerId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/share'
    | '/teams/new'
    | '/games/$gameId/fairness'
    | '/games/$gameId/summary'
    | '/teams/$teamId/new-game'
    | '/teams/$teamId/roster'
    | '/teams/$teamId/season'
    | '/teams/$teamId/settings'
    | '/games/$gameId/'
    | '/teams/$teamId/players/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ShareRoute: typeof ShareRoute
  TeamsNewRoute: typeof TeamsNewRoute
  GamesGameIdFairnessRoute: typeof GamesGameIdFairnessRoute
  GamesGameIdSummaryRoute: typeof GamesGameIdSummaryRoute
  TeamsTeamIdNewGameRoute: typeof TeamsTeamIdNewGameRoute
  TeamsTeamIdRosterRoute: typeof TeamsTeamIdRosterRoute
  TeamsTeamIdSeasonRoute: typeof TeamsTeamIdSeasonRoute
  TeamsTeamIdSettingsRoute: typeof TeamsTeamIdSettingsRoute
  GamesGameIdIndexRoute: typeof GamesGameIdIndexRoute
  TeamsTeamIdPlayersPlayerIdRoute: typeof TeamsTeamIdPlayersPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/new': {
      id: '/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof TeamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/': {
      id: '/games/$gameId/'
      path: '/games/$gameId'
      fullPath: '/games/$gameId/'
      preLoaderRoute: typeof GamesGameIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/fairness': {
      id: '/games/$gameId/fairness'
      path: '/games/$gameId/fairness'
      fullPath: '/games/$gameId/fairness'
      preLoaderRoute: typeof GamesGameIdFairnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/summary': {
      id: '/games/$gameId/summary'
      path: '/games/$gameId/summary'
      fullPath: '/games/$gameId/summary'
      preLoaderRoute: typeof GamesGameIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/new-game': {
      id: '/teams/$teamId/new-game'
      path: '/teams/$teamId/new-game'
      fullPath: '/teams/$teamId/new-game'
      preLoaderRoute: typeof TeamsTeamIdNewGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/roster': {
      id: '/teams/$teamId/roster'
      path: '/teams/$teamId/roster'
      fullPath: '/teams/$teamId/roster'
      preLoaderRoute: typeof TeamsTeamIdRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/season': {
      id: '/teams/$teamId/season'
      path: '/teams/$teamId/season'
      fullPath: '/teams/$teamId/season'
      preLoaderRoute: typeof TeamsTeamIdSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/settings': {
      id: '/teams/$teamId/settings'
      path: '/teams/$teamId/settings'
      fullPath: '/teams/$teamId/settings'
      preLoaderRoute: typeof TeamsTeamIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/players/$playerId': {
      id: '/teams/$teamId/players/$playerId'
      path: '/teams/$teamId/players/$playerId'
      fullPath: '/teams/$teamId/players/$playerId'
      preLoaderRoute: typeof TeamsTeamIdPlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ShareRoute: ShareRoute,
  TeamsNewRoute: TeamsNewRoute,
  GamesGameIdFairnessRoute: GamesGameIdFairnessRoute,
  GamesGameIdSummaryRoute: GamesGameIdSummaryRoute,
  TeamsTeamIdNewGameRoute: TeamsTeamIdNewGameRoute,
  TeamsTeamIdRosterRoute: TeamsTeamIdRosterRoute,
  TeamsTeamIdSeasonRoute: TeamsTeamIdSeasonRoute,
  TeamsTeamIdSettingsRoute: TeamsTeamIdSettingsRoute,
  GamesGameIdIndexRoute: GamesGameIdIndexRoute,
  TeamsTeamIdPlayersPlayerIdRoute: TeamsTeamIdPlayersPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
